INSERT INTO ALUNO (NOME, EMAIL, DATA_CADASTRO) VALUES ('Leonardo', 'leo@gmail.com', '2024-06-09' );
INSERT INTO ALUNO (NOME, EMAIL, DATA_CADASTRO) VALUES ('Rodrigo', 'rodrigo@gmail.com', '2024-07-05' );
INSERT INTO ALUNO (NOME, EMAIL, DATA_CADASTRO) VALUES ('Anderson', 'anderson@gmail.com', '2024-09-04' );
INSERT INTO ALUNO (NOME, EMAIL, DATA_CADASTRO) VALUES ('William', 'william@gmail.com', '2024-10-09' );
INSERT INTO ALUNO (NOME, EMAIL, DATA_CADASTRO) VALUES ('Cristiano', 'cristiano@gmail.com', '2024-08-18' );
INSERT INTO ALUNO (NOME, EMAIL, DATA_CADASTRO) VALUES ('Aloisio', 'aloisio@gmail.com', '2024-11-11' );
INSERT INTO ALUNO (NOME, EMAIL, DATA_CADASTRO) VALUES ('Marcelo', 'marcelo@gmail.com', '2024-08-20' );
INSERT INTO ALUNO (NOME, EMAIL, DATA_CADASTRO) VALUES ('Renan', 'renan@gmail.com', '2024-07-11' );
INSERT INTO ALUNO (NOME, EMAIL, DATA_CADASTRO) VALUES ('Carlos', 'carlos@gmail.com', '2024-11-21' );
INSERT INTO ALUNO (NOME, EMAIL, DATA_CADASTRO) VALUES ('Marcos', 'marcos@gmail.com', '2024-08-14' );
INSERT INTO ALUNO (NOME, EMAIL, DATA_CADASTRO) VALUES ('João', 'joao@gmail.com', '2024-07-10' );




INSERT INTO CURSO (NOME, DESCRICAO, DATA_CRIACAO) VALUES ('SAP', 'Software de gestão de processos empresariais', '2024-12-13' );
INSERT INTO CURSO (NOME, DESCRICAO, DATA_CRIACAO) VALUES ('JAVA', 'Linguagem de programação e plataforma de computação que permite desenvolver e executar programas', '2018-02-01' );
INSERT INTO CURSO (NOME, DESCRICAO, DATA_CRIACAO) VALUES ('AWS', 'Plataforma de computação em nuvem que oferece uma ampla variedade de serviços de datacenters em todo o mundo', '2019-03-04' );




INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 1, 1, '2024-11-01' );
INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 2, 2, '2024-11-02' );
INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 3, 3, '2024-11-03' );
INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 4, 1, '2024-11-04' );
INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 5, 2, '2024-11-05' );
INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 6, 3, '2024-11-06' );
INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 7, 1, '2024-11-07' );
INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 8, 2, '2024-11-08' );
INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 9, 3, '2024-11-09' );
INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 10, 1, '2024-11-10' );
INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 1, 2, '2024-11-11' );
INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 2, 3, '2024-11-12' );
INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 3, 1, '2024-11-13' );
INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 4, 2, '2024-11-14' );
INSERT INTO INSCRICAO (ALUNO_ID, CURSO_ID, DATA_INSCRICAO) VALUES ( 5, 3, '2024-11-15' );